### ISSUE TITLE
Compatibility of the bundle with php 7.0

### ISSUE THREAD

**Issue by iamakanksha** [ggergo/SqlIndexHintBundle#2]
Is there a specific reason why support has not been provided for php 7.0 and provided only for php 7.1 and above? If there are are no issues then can the support be extended to php 7.0 as well?
@ggergo @albertboada

**Comment by ggergo** [comment]
Hi Akanksha! The bundle was built on doctrine/orm v2.6 which is the latest major release expecting no further features before v3.0. Doctrine/orm v2.6 also requires PHP 7.1+. Currently PHP 7.3 is the last supported version by PHP (security only) and 7.4 is the last actively supported version. Therefore I have no plan adding support for 7.0 I hope you understand and I hope you can upgrade to 7.3 at least.
